version: "3"
services:
  # NextJS exported app running on an nginx webserver
  acap-client-prod:
    container_name: acap-client-prod
    image: amia/acap-client:latest
    env_file:
      - ./client/.env
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.acap
      target: production
    networks:
      - acap-prod
    ports:
      - "3000:3000"

  # Express web server app running in production mode
  acap-server-prod:
    container_name: acap-server-prod
    image: amia/acap-server:latest
    restart: always
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile.acap
      target: production
    networks:
      - acap-prod
    ports:
      - "3001:3001"

networks:
  acap-prod:
    name: acap-prod
    external: false
