# .github/workflows/scheduled-cyclone.yml
# This workflow runs a web scraper script that parses PAGASA's Tropical Cyclone Bulletin web page
# and uploads relevant cyclone data to Firestore
name: CRON Scrape and Update Cyclone Information

on:
  schedule:
    # Runs "At minute 0 past every 2nd hour."
    - cron: '0 */2 * * *'

env:
  AXIOS_SSL_REJECT_INVALID: ${{ secrets.AXIOS_SSL_REJECT_INVALID }}
  EMAIL_WHITELIST: ${{ secrets.EMAIL_WHITELIST }}
  REGION_NAME: ${{ secrets.REGION_NAME }}
  PROVINCES: ${{ secrets.PROVINCES }}
  PROVINCES_ARCHIVE: ${{ secrets.PROVINCES_ARCHIVE }}
  IS_RMCAS_API_ACTIVE: ${{ secrets.IS_RMCAS_API_ACTIVE }}

jobs:
  update-typhoon-dev:
    name: Scrape and Update Cyclone Advisory (Development)
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACC: ${{ secrets.FIREBASE_SERVICE_ACC_DEV }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY_DEV }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: |
          cd server
          npm install
      - name: Run script
        run: |
          cd server
          npm run cron:cyclone
      - name: Run cleanup script
        if: env.IS_RMCAS_API_ACTIVE == '1'
        run: |
          cd server
          npm run cron:clean:special

  update-typhoon-prod:
    name: Scrape and Update Cyclone Advisory (Production)
    needs: update-typhoon-dev
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACC: ${{ secrets.FIREBASE_SERVICE_ACC_PROD }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY_PROD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with: # TO-DO: Fine tune with @latest specific release tag reference (i.e., v9.4.5)
          ref: 'master'
      - name: Use NodeJS v16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: |
          cd server
          npm install
      - name: Run script
        run: |
          cd server
          npm run cron:cyclone
      - name: Run cleanup script
        if: env.IS_RMCAS_API_ACTIVE == '1'
        run: |
          cd server
          npm run cron:clean:special
